config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user
   
   validates :title, {presence: true}
   validates :body, {presence: true,length: { maximum: 200 }}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, {length: { in: 2..20 },uniqueness: true}
  validates :introduction, {length: { maximum: 50 }}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new = Book.new
  end

  def new

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to "/books/#{@book.id}"
     else
       @books = Book.all
       render("books/index")
     end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
  @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
   redirect_to book_path(@book.id)
   else
   render("books/edit")
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
    def user_params
        params.require(:user).permit(:name, :profile_image, :introduction)
    end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
        @book = Book.new
    end

    def show
        @user = User.find(params[:id])
        @books = @user.books
        @book = Book.new
    end
        
    def create
        @book = Book.new(book_params)
        if @book.save
         flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
        else
         @books = Book.all
         render("books/index")
        end
    end

    def edit
        @user = User.find(params[:id])
        if @user == current_user
            render "edit"
        else
            redirect_to user_path(current_user)
        end
    end
    
    def update
        @user = User.find(params[:id])
         if @user.update(user_params)
            flash[:notice] = "You have updated user successfully."
            redirect_to user_path(@user.id)
         else
         render("users/edit")
         end
    end
    
    private

    def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
    end
    
    def book_params
    params.require(:book).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <main>
  <p id="notice"></p>
  <% if @book.errors.any? %>
  <div id="error_explanation">
   <ul>
    <%= @book.errors.count %>errors prohibited this book from being saved:
     <% @book.errors.full_messages.each do |message| %>
      <li>
       <%= message %>
      </li>
     <% end %>
    <% end %>
   </ul>
  </div>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <%= form_with model:@book,local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title,class:"form-control book_title" %>
          </div>
          <div class="field">
             <label for="form-group">Opinion</label>
             <%= f.text_area :body,class:"form-control book_body" %>
          </div>
          <div class="action">
             <%= f.submit "Update Book",class:"btn btn-success" %>
          </div>
        <% end %>

  <%= link_to("Show","/books/#{@book.id}") %>
   |
  <%= link_to("Back","/books") %>
    </div>
   </div>
  </div>
 </main>

app/views/books/index.html.erb
<main>
 <p id="notice"></p>
 <% if flash[:notice] %>
   <div class="flash">
     <%= flash[:notice] %>
   </div>
 <% end %>
 
 <% if @book.errors.any? %>
  <div id="error_explanation">
   <ul>
    <%= @book.errors.count %>errors prohibited this book from being saved:
     <% @book.errors.full_messages.each do |message| %>
      <li>
       <%= message %>
      </li>
     <% end %>
    <% end %>
   </ul>
  </div>
 
 <div class="container px-5 px-sm-0">
  <div class="row">
   <%= render 'users/list', user: current_user, book: @book %>
   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
        <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
        </tr>
       </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to "/users/#{book.user_id}" do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
            </td>
            <td><%= link_to "/books/#{book.id}" do %>
                <%= book.title %>
                <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
     </table>
   </div>
  </div>
 </div>
</main>

app/views/books/show.html.erb
<main>
    
    <p id="notice"></p>
    <% if flash[:notice] %>
      <div class="flash">
    <%= flash[:notice] %>
    
      </div>
    <% end %>
    <div class="container">
        <div class="row">
            <%= render 'users/list',user: @user,book: @new %>
            <div class="col-md-8 offset-md-1">
                <h2>Book detail</h2>
                <table class="table">
                    <tbody>
                        <tr>
                          <td>
                            <%= link_to "/users/#{@user.id}" do %>
                            <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                            <br>
                            <%= @user.name %>
                            <% end %>
                          </td>
                          <td>
                              <%= @book.title %>
                          </td>
                          <td>
                              <%= @book.body %>
                          <td>
                          <% if @user.id == current_user.id %>
                           <%= link_to "Edit",edit_book_path(@book.id),class:"btn btn-sm btn-success edit_book_26608"%>
                          <% end %>
                          </td>
                          <td>
                           <% if @user.id == current_user.id %>
                           <%= link_to "Destroy",book_path(@book.id), method: :delete,"data-confirm" => "Are you sure?",class:"btn btn-sm btn-danger destroy_book_26608"%>
                           <% end %>
                          </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>







    

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
    </div>
<% end %>

<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">
            Welcome to
            <i class="fas fa-book"></i>
            <strong>Bookers</strong>
            !!
        </h1>
    </div>
</div>

</main>

app/views/homes/top.html.erb
 <main>
  <p id="notice"></p>
   <% if flash[:notice] %>
   <div class="flash">
   <%= flash[:notice] %>
   </div>
  <% end %>

  <div class="container">
   <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1> Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
          !!
      </h1>
      <p> In
       <i class="fas fa-book"></i>
          <strong>Bookers</strong>
           ,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
       <div class="row">
        <%= link_to "Log in",new_user_session_path,class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
       </div>
       <div class="row">
        <%= link_to "Sign Up",new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up" %>
       </div>
      </div>
    </div>
   </div>
  </div>
 </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class ="container">
       <% if user_signed_in? %>
           <%= link_to root_path,class:"navbar-brand" do %>
           <span>Bookers</span>
           <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
               <li>
                 <%= link_to "Home", user_path(current_user.id),class:"fas fa-home nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "Users", users_path,class:"fas fa-users nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "Books", books_path,class:"fas fa-book-open nav-link text-light" %>
               </li>
               <li>
                 <%= link_to "logout", destroy_user_session_path, method: :delete,class:"fas fa-sign-out-alt nav-link text-light" %>
               </li>
            </ul>
          </div>
       <% else %>

           <%= link_to root_path,class:"navbar-brand" do %>
           <span>Bookers</span>
           <% end %>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
              <li>
                <%= link_to "Home", root_path,class:"fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to("About", "/home/about",class:"fas fa-link nav-link text-light") %>
                </li>
              <li>
                <%= link_to "sign up", new_user_registration_path,class:"fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light" %>
              </li>
           </ul>
         </div>
       <% end %>
     </div>
   </nav>
 </header>
 <%= yield %>


    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_list.html.erb
 <div class="col-md-3">
  
  
    <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <div class="profile-container">
    <table class="table">
     <tbody>
      <tr></tr>
      <tr>
       <th>name</th>
       <th><%= user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
     </tbody>
    </table>
   </div>
   
  <div class="row">
   
     <%= link_to "", edit_user_path(user),class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_31924" %>
    
  </div>
  
  
    <h2 class="mt-3">New book</h2>
    
    
    <%= form_with model:book,local:true do |f| %>
      <div class="form-group">
       <label for="book_title">Title</label>
        <%= f.text_field :title,class:"form-control book_title" %>
      </div>
      <div class="form-group">
       <label for="book_opinion">Opinion</label>
        <%= f.text_area :body,class:"form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book",class:"btn btn-success" %>
      </div>
    <% end %>
    
    </div>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>

  <% if @user.errors.any? %>
  <div id="error_explanation">
   <ul>
    <%= @user.errors.count %>errors prohibited this book from being saved:
     <% @user.errors.full_messages.each do |message| %>
      <li>
       <%= message %>
      </li>
     <% end %>
    <% end %>
   </ul>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>

        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
              <label for="inputName">Name</label>
              <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name",class:"form-control name" %>
          </div>
          <div class="form-group">
              <label for="inputImage">ProfileImage</label>
              <%= f.attachment_field :profile_image, placeholder: "Image",class:"form-control-file user_image" %>
          </div>
          <div class="form-group">
              <label for="inputIntroduction">Introduction</label>
              <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction",class:"form-control introduction"%>
          </div>
          <div class="form-group">
            <%= f.submit "Update User",class:"btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
    <p id="notice"></p>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <%= render 'users/list',user: current_user, book: @book %>
            <div class="col-md-8 offset-md-1">
                <h2>Users</h2>
                <table class="table">
                     <thead>
                         <tr>
                            <th>image</th>
                            <th>name</th>
                            <th colspan="3"></th>
                         </tr>
                     </thead>
                    <tbody>
                        <% @users.each do |user| %>
                            <tr>
                                <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %></td>
                                <td><%= user.name %></td>
                                <td><%= link_to "Show","/users/#{user.id}" %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>



 

app/views/users/show.html.erb
<main>
 <p id="notice"></p>
  <% if flash[:notice] %>
    <div class="flash">
  <%= flash[:notice] %>
    </div>
  <% end %>

  <% if @book.errors.any? %>
  <div id="error_explanation">
   <ul>
    <%= @book.errors.count %>errors prohibited this book from being saved:
     <% @book.errors.full_messages.each do |message| %>
      <li>
       <%= message %>
      </li>
     <% end %>
    <% end %>
   </ul>
  </div>


 <div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list',user: @user,book: @book %>
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
        <thead>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
         <% @books.each do |book| %>
         <tr>
           <td>
            <%= link_to "/users/#{@user.id}" do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
           </td>
           <td>
            <%= link_to "/books/#{book.id}" do %>
            <%= book.title %>
            <% end %>
           </td>
           <td>
            <%= book.body %>
           </td>
         </tr>
         <% end %>
        </tbody>
       </table>
    </div>
  </div>
 </div>
</main>